import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import './globals.css';
import { AppSidebar, PageHeader } from '@/components/app-navigation';
import { ThemeProvider } from '@/components/theme-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import DynamicCrumbs from '@/components/dynamicBreadCrumb';
import { SearchBar } from '@/components/search-bar';
import Notifications from '@/components/notifications';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-dvh antialiased`}
      suppressHydrationWarning
    >
      <body className="h-full flex flex-col">
        <TooltipProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider className="flex-1 min-h-0">
              <AppSidebar />
              <SidebarInset className="flex flex-col min-h-0">
                <header className="z-50 sticky top-0 flex h-16 shrink-0 items-center gap-2 border-b px-4 justify-between backdrop-blur-md">
                  <div className="flex items-center gap-2 px-4">
                    <SidebarTrigger className="-ml-1" />
                    <DynamicCrumbs />
                  </div>
                  <div className="flex space-x-2">
                    <SearchBar />
                    <Notifications />
                  </div>
                </header>
                <div className="flex-1 min-h-0 overflow-y-auto flex flex-col p-6 gap-6">
                  <PageHeader />
                  {children}
                </div>
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
